project:
  type: website

website:
  title: Anomaly Detection for Equine Gait Abnormalities
  navbar:
    right:
      - icon: github
        href: https://github.com/INFO-523-SU24/final-project # Need to change to your project repo
    left:
      - text: Project
        href: index.qmd
      - text: Code
        menu:
          - text: Feature Engineering
            href: analysis/01_features.qmd
          - text: Anomaly Detection
            href: analysis/02_anomalies.qmd
      - text: Proposal
        href: proposal.qmd
      - text: Presentation
        href: presentation.qmd
      - text: About
        href: about.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true

execute:
  freeze: auto
